version: '3.8'

services:
  postgres:
    container_name: restful-api-users-java-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restful_users