services:
  postgres:
    container_name: restful-api-users-java-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restful_users
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  api:
    container_name: restful-api-users-java-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    env_file:
      - ./src/main/resources/application-dev.properties
    volumes:
      - ./src/main/resources/public:/app/uploads
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata: